# Generated by Django 4.0.6 on 2022-12-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
