# Generated by Django 4.1.4 on 2022-12-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
