# Generated by Django 4.1.4 on 2022-12-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accommodation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
