# Generated by Django 3.2.16 on 2023-02-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_auto_20230125_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
